# Generated by Django 2.0.4 on 2018-04-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reaction',
            new_name='agree',
        ),
    ]
